### ISSUE TITLE
Please remove duplicated Handlebarsjs each helper

### ISSUE THREAD

**Issue by webxl** [assemble/handlebars-helpers#130]
In my assemble task template, I just wanted to use the @first and @last variables described here:
https://github.com/wycats/handlebars.js/pull/661and looks like this project's ``{{#each}}`` is overriding the built-in handlebars helper.

**Comment by doowb** [comment]
Sounds like this was resolved, since `{[each}}` was removed in the refactor. I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
