### ISSUE TITLE
How would I go about integrating this to Ember?

### ISSUE THREAD

**Issue by duizendnegen** [assemble/handlebars-helpers#159]
I'm using Ember-CLI and I am currently failing to get this absolute goldmine working. `npm install --save-dev handlebars-helper` registers it in my package, but building with a pointer to the library from my `Brocfile.js` is no use it seems.

Any pointers on what would be the right way to go about doing this?

**Comment by jonschlinkert** [comment]
closing due to age and significant changes in the pending release
