### ISSUE TITLE
Update to handlebars v2.0

### ISSUE THREAD

**Issue by pspi** [assemble/handlebars-helpers#173]
How about updating to latest handlebars? I'm especially looking for added support for partials parameters in 2.0.

**Comment by stewx** [comment]
+1

**Comment by jonschlinkert** [comment]
take a look at the [dev branch](https://github.com/assemble/handlebars-helpers/tree/dev), everything is latest. dev is ready to ship except for docs (it has full docs in the readme, but not on the website). Feedback would be great.

**Comment by doowb** [comment]
Sounds like this was resolved, since the refactor uses the latest Handlebars and also allows passing in your own version of Handlebars. I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
