### ISSUE TITLE
Warning: Missing helper: 'doctype' Use --force to continue.

### ISSUE THREAD

**Issue by alycda** [assemble/handlebars-helpers#177]
I'm unable to use any this (and other) helper(s) with Assemble. Why is there no reference to this helper within lib/helpers/helpers-html.js , but it is documented in docs/helpers/html/helper-doctype.md ?

**Comment by jonschlinkert** [comment]
What version of assemble are you using? with grunt? gulp? standalone?

**Comment by alycda** [comment]
Assemble: 0.4.42
Grunt: 0.4.5

**Comment by doowb** [comment]
Looks like the `doctype` helper was removed and the documentation hasn't been updated yet.

**Comment by doowb** [comment]
Closing due to age and the `{{doctype}}` helper has been removed and the README no longer refers to it.
