### ISSUE TITLE
`grunt` missing from package.json

### ISSUE THREAD

**Issue by jeremiahlee** [assemble/handlebars-helpers#186]
index.js requires './lib/helper-lib' which requires './utils/utils' which requires grunt on line 18.

grunt is not a dependency in package.json.

**Comment by zzswang** [comment]
same problem

**Comment by Friend-LGA** [comment]
same problem

**Comment by TangMonk** [comment]
same issue

**Comment by ChristianRich** [comment]
+1

**Comment by shnist** [comment]
+1

**Comment by keithamus** [comment]
The [dev branch](https://github.com/assemble/handlebars-helpers/tree/dev) no longer requires Grunt. I'm going to quote @jonschlinkert's [comment on another issue here](https://github.com/assemble/handlebars-helpers/issues/206#issuecomment-157898260):

>  If you or anyone else would like to help, I'm open to someone helping maintain the current branch so we can stay focused on getting the next release published. just let us know

@jonschlinkert I think this one should be closed, just like #206 is. See also #157 #187
