### ISSUE TITLE
Highlight helper not working

### ISSUE THREAD

**Issue by alejandroiglesias** [assemble/handlebars-helpers#190]
I'm trying to use the highlight helper but it's just not outputting anything:

```
{{#highlight}}
<div>my code</div>
{{/highlight}}
```

Is there any config needed or some idea of why it's not working?
Thanks.

**Comment by doowb** [comment]
There isn't a `{{highlight}}` helper in this library.

**Comment by alejandroiglesias** [comment]
Sorry then, probably a plugin coming from the stack I was using, probably from template-helpers. Thanks.
