### ISSUE TITLE
Missing documentation on extend/block/content?

### ISSUE THREAD

**Issue by tBaxter** [assemble/handlebars-helpers#196]
Following the examples on https://github.com/assemble/handlebars-helpers/blob/master/docs/helpers/layout/helper-extend.md, I cannot find a way to make this work. 

I have the partial exactly as in the example. I have a page extending it exactly as shown in the example under "Extending template:"

Is "Extending template:" supposed to be a page, or something else? And what is the base layout supposed to look like in this scenario? 

Can the docs be updated to walk me through how this is supposed to work, because right now, they don't mention the underlying layout at all, and the use of "template" is unclear.. is that supposed to be a page? And if it's not a page, then what does the page with content look like. 

Yeah, I'm a little frustrated. I've spent two days on this now, and doing exactly what's shown in the examples, it will not work for me.

**Comment by tBaxter** [comment]
Update: with some trial and error, I've got something partially working.

In my base layout, it is simply 
     {{> body }}

a partials/base_partial.hbs is defining the page structure (much like page_foundation in the example) and a page can successfully extend that and fill in the blocks.

However, I still don't really know if that setup is correct -- especially the base layout, and I'm unable to have a section_base extend the base, and then have a page extend that section base.

**Comment by doowb** [comment]
Any layouts that you want to use with these helpers need to be registered as partials in assemble. Assemble uses a different layout system that builds up the entire template string before passing it to handlebars to compile and render.

These helpers work by internally rendering the templates (pages) to dynamically register partials with handlebars. Then they re-render the templates with the newly register partials to fill in the content areas.

I would suggest only using a `base` layout with `{{> body}}` in the assemble build, and register all your other layouts as partials that you want to use with these helpers. You should be able to do nested extends with the partial layout templates that are registered. Then in your pages, you can extend the child most partial layout in your stack.

I hope that doesn't confuse you more.

**Comment by tBaxter** [comment]
Thanks. I believe I have this working now. Feel free to close the ticket, although I would still like to see additional docs added, particularly on handling the base layout with {{>body}} and the difference between {{{foo}}}, {{#block foo }} and {{>foo}} and expected behavior with each. Thanks again.

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems

In the refactor the layout helpers were removed. You can use [this library](https://github.com/shannonmoeller/handlebars-layouts) instead.
