### ISSUE TITLE
TypeError: Cannot read property 'sort' of undefined

### ISSUE THREAD

**Issue by leocreatini** [assemble/handlebars-helpers#197]
I found this error and a similar one for 'marked' instead of 'sort'. Was able to fix it by adding:

<b>helper-lib.js</b>
```
line 25, options = (typeof options !== 'undefined') ? options : {};
```

<b>helpers-collections.js</b>
```
line 264, array = (typeof array !== 'undefined') ? array : [];
```

Not sure if anyone else experienced this, but hope it saves others' hours.

**Comment by doowb** [comment]
Sounds like this was resolved, since the library was refactored. I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems

**Comment by shaigh-mw** [comment]
Since I am seeing this issue as well, Please be so kind as to give those who are are not so familiar with the structure of assemble by specifying where and how you added:

helper-lib.js
helpers-collections.js

Cheers!

**Comment by mstafaben** [comment]
[Bouyguestelecom_Facture_20200602.pdf](https://github.com/helpers/handlebars-helpers/files/4731886/Bouyguestelecom_Facture_20200602.pdf)
