### ISSUE TITLE
handlebars does not support render.

### ISSUE THREAD

**Issue by ceehaupt** [assemble/handlebars-helpers#199]
When I'm running grunt this warning is shown:
Running "assemble:dev" (assemble) task
    handlebars does not support render.
    Assembling build/index.html ERROR
    Warning: handlebars does not support render. Use --force to continue.

**Comment by johnyb** [comment]
For the record, the actual error would be:

```
> helper = require('handlebars-helpers')
TypeError: Cannot read property '1' of null
    at Object.exports.getVersion (/home/jb/projects/ox/appsuite/ui/node_modules/handy/index.js:26:84)
    at Object.<anonymous> (/home/jb/projects/ox/appsuite/ui/node_modules/to/lib/to.js:76:25)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/jb/projects/ox/appsuite/ui/node_modules/to/index.js:4:18)
    at Module._compile (module.js:435:26)
```

**Comment by johnyb** [comment]
After debugging this, I came to the following conclusion:

* https://github.com/openmason/handy exports getVersion, which is broken with latest npm.
* https://github.com/openmason/to uses getVersion, which propably should export the version of "to" library, which it does not.
* this only happens with npm@>3, because it brings flat node_modules/ and therefor the package.json of the actual project is evaluated.

As a work-around, use only decimals and dots in the version string of your package.json. We use a dash to indicate patch releases, which results in the above error.

**Comment by jonschlinkert** [comment]
great to know, thanks for the additional detail @johnyb

**Comment by johnyb** [comment]
Another work-around (which is what I implemented, until the bugs in handy/to are fixed) would be to use npm shrinkwrap and patch the file like this:

```diff
-    "handy": {
-      "version": "0.0.13",
-      "from": "handy@>=0.0.11",
-      "resolved": "https://registry.npmjs.org/handy/-/handy-0.0.13.tgz"
-    },
     "har-validator": {
       "version": "2.0.2",
       "from": "har-validator@>=2.0.2 <2.1.0",
@@ -3320,7 +3315,14 @@
     "to": {
       "version": "0.2.9",
       "from": "to@>=0.2.9 <0.3.0",
-      "resolved": "https://registry.npmjs.org/to/-/to-0.2.9.tgz"
+      "resolved": "https://registry.npmjs.org/to/-/to-0.2.9.tgz",
+      "dependencies": {
+        "handy" : {
+          "version": "0.0.13",
+          "from": "handy@>=0.0.11",
+          "resolved": "https://registry.npmjs.org/handy/-/handy-0.0.13.tgz"
+        }
+      }
     },
```

This basically forces npm to install handy into `node_modules/to/node_modules/handy`, so getVersion will work like in environments with npm@<3

**Comment by ceehaupt** [comment]
For the record my problem was fixed by updating node, xcode and several versions in my package.json
