### ISSUE TITLE
Output of {{embed}} formatted incorrectly?

### ISSUE THREAD

**Issue by Bendihossan** [assemble/handlebars-helpers#201]
I'm having issues using `{{embed}}` with `grunt-assemble`.

What I'd expect is that when I call something like `{{embed 'src/handlebars/partials/components/breadcrumb-partial.hbs'}}` the content of that file is rendered within a `<pre><code></code></pre>` block. That's the impression I got from reading [assemble.io/docs/Embedding-Code.html](http://assemble.io/docs/Embedding-Code.html) anyway. What happens for me is the content of the file handlebars file is printed to the page. I actually get the following:

``````
```hbs {{!-- Breadcrumb Use as follows: {{>breadcrumb-partial breadcrumb}} where context would be defined in the yaml front matter as follows: --- breadcrumb: - First - Second - Last --- All but the last item in the breadcrumb will be rendered as a link. --}} <div class="row"> <div class="col-md-12"> <div class="breadcrumb"> <p class="breadcrumb__item">You are here:</p> <a href="#" class="breadcrumb__item">Home</a> <ol> {{#each this}} <li class="breadcrumb__separator">/</li> {{#if @last}} <li class="breadcrumb__item">{{ title }}</li> {{else}} <li class="breadcrumb__item"><a href="#">{{ title }}</a></li> {{/if}} {{/each}} </ol> </div> </div> </div> ```
``````

The above renders without being formatted into a pre/code block and so is simply text on a page.

I looked at the options for Marked and tried changing `gfm` to false to see if this was causing it but it didn't make a difference. My config I'm passing to Assemble for Marked here (copied from [assemble.io/docs/options-marked.html](http://assemble.io/docs/options-marked.html)):

``` js
marked: {
    breaks: false,
    gfm: false,
    highlight: function (lang, code) {
        return hljs.highlightAuto(lang, code).value;
    },
    langPrefix: 'language-',
    pedantic: false,
    sanitize: false,
    silent: false,
    smartLists: false,
    smartypants: false,
    tables: true
}
```

I am using the following versions:
- handlebars-helpers: "^0.5.8"
- assemble: "^0.6"
- grunt-assemble: "~0.4.0"

I'm not sure if what I believe to be expected is correct and if not what the expected behaviour is supposed to be.

**Comment by doowb** [comment]
@Bendihossan sorry for the late reply.

Do you have an example repo of this? Since the refactor the code looks like it will add the newlines correctly. You're also listing 2 different versions of `assemble` so I'm not sure what the rest of your setup looks like.

If you've solved this already, please let me know and I'll close the issue.

**Comment by Bendihossan** [comment]
No longer have an example of this unfortunately (it was something I worked on at a previous employer) so agree this can be closed now
