### ISSUE TITLE
join helper doesn't work in Handlebars 2.0+

### ISSUE THREAD

**Issue by stewx** [assemble/handlebars-helpers#202]
I get output like this when using the joinAny function: [object Object],[object Object],[object Object]
http://jsfiddle.net/stewx/umj3Lbb0/

**Comment by jonschlinkert** [comment]
Would you mind trying out the `join` helper on the dev branch? see if that works for you?

**Comment by doowb** [comment]
Sounds like this was resolved, since the lib was refactored. See the [new README docs](https://github.com/assemble/handlebars-helpers#join) on usage.

I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
