### ISSUE TITLE
"or" helper could take in any number of parameters

### ISSUE THREAD

**Issue by tteltrab** [assemble/handlebars-helpers#203]
It would be nice to have the "or" helper allow for passing in 2+ options to conditionally check, rather than allowing for just 2.  For example, 

    {{#or thisIsFale thisIsFalse thisIsTrue }}
        {{> some-partial }}
    {{/or}}

I suppose this is a similar use case as that for the undocumented `ifAny` helper?  As far as I could tell, it allowed you to make comparisons, but didn't allow for the simple case of checking if any of 3 passed in options are true/exist.

**Comment by doowb** [comment]
PR for this is welcome.

**Comment by spacedawwwg** [comment]
This was suggest as an addition in #165

**Comment by spacedawwwg** [comment]
This has been implemented from v0.7.0
