### ISSUE TITLE
Missing documentation for installation

### ISSUE THREAD

**Issue by ChristianRich** [assemble/handlebars-helpers#205]
How do you install this with Express 4?
This is my setup:

    var express = require('express')
		, app = express()
		, exphbs = require('express-handlebars');

	var hbs = exphbs.create({
		extname: '.hbs',
		defaultLayout: 'default',
		layoutsDir: './lib/templates/layouts',
		partialsDir: './lib/templates/partials'
		helpers: require('handlebars-helpers') // Not registering correctly
	});

In a template:
{{lowercase "MAKE THIS ALL LOWERCASE"}}

Yields:
Error: Missing helper: "lowercase"

**Comment by maban** [comment]
This has me stumped too. There's a step missing in the documentation after installing the package. :(

**Comment by keithamus** [comment]
As a workaround for now, you could try:

```js
var express = require('express')
    , app = express()
    , exphbs = require('express-handlebars');

var hbs = exphbs.create({
    extname: '.hbs',
    defaultLayout: 'default',
    layoutsDir: './lib/templates/layouts',
    partialsDir: './lib/templates/partials'
});
require('handlebars-helpers').register(hbs);
```

**Comment by maban** [comment]
Thank you, I'll give this a go! :)

**Comment by rsteckler** [comment]
Super frustrating.  Here's what finally worked for me:
```
var handlebarsCore=require('handlebars');
require('handlebars-helpers').register(handlebarsCore, {});
```

**Comment by rsteckler** [comment]
Slight correction to the above:
```
var app = express();

var exphbs = require('express-handlebars');
var hbs = exphbs.create({
  defaultLayout: 'main',
  layoutsDir: path.resolve(__dirname, 'views/layouts')
});

//express-handlebars exposes the handlebars instance as below.
var handlebars = hbs.handlebars;

var handlebarHelpers = require('handlebars-helpers');
//Note the empty object is required to avoid a crash.
handlebarHelpers.register(handlebars, {});

```

**Comment by rsteckler** [comment]
I take it back.  It appears that handlebars-helpers won't work correctly with handlebars-express.  For example, the {{#extend}} function internally tries to iterate handlebars.partials.  Unfortunately, handlebars-express doesn't "update" that internal collection and instead exposes it's own version (getPartials(), which is asynchronous).  Giving up for now.

**Comment by doowb** [comment]
Sounds like this was resolved, since the library has been refactored.
The [new usage docs](https://github.com/assemble/handlebars-helpers#usage) shows how you can get an object of all the helpers and then use that directly in your `express-handlebars` config:

```js
var express = require('express')
    , app = express()
    , exphbs = require('express-handlebars');

var hbs = exphbs.create({
    extname: '.hbs',
    defaultLayout: 'default',
    layoutsDir: './lib/templates/layouts',
    partialsDir: './lib/templates/partials'
    helpers: require('handlebars-helpers')() // make sure to call the returned function
});
```

I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems

**Comment by yairEO** [comment]
none-the-less there is a missing step in the docs, for those who use handles in the client (and not in the server).

Nothing about **registering** is mentioned.
