### ISSUE TITLE
how to Register custom helpers assemble 0.17.1

### ISSUE THREAD

**Issue by majabee** [assemble/handlebars-helpers#238]
In my assemblefile.js I try to register a custom helper. The helper itself does work since i have it in use in a grunt project with assemble.
assemble: {
  options: {
    helpers: ['./src/helper/custom-helper.js' ]
  }
}
In assemble  0.17.1 I tried it like this but it doesn´t work does anyone know how to?
app.helpers('./src/helper/custom-helper.js');

**Comment by jonschlinkert** [comment]
Please ask implementation related questions on stackoverflow. (this question is related to assemble more than handlebars-helpers. Please use the `handlebars` and `assemble` tags on SO)
