### ISSUE TITLE
How can I use it without node

### ISSUE THREAD

**Issue by cristiangrojas** [assemble/handlebars-helpers#36]
Hi, thanks for this awesome collection of helpers.

I'm doing a project in Django, I use Backbone.js inside of the project and my javascript template renderer is Handlebars.

I need to use this helpers importing them with require.js but I don't know the way to do it, can you guide me please?

**Comment by jonschlinkert** [comment]
Technically you can't, unless you only need the helpers in that lib. Swag is awesome, but there are like 70 helpers here that aren't in swag

**Comment by doowb** [comment]
You can use `browserify` to package this library up to use it in a browser. Take a look at [this example](https://github.com/doowb/handlebars-helpers-browserify-example) for more information.

Closing this issue. Please open a new issue if you find a bug.

**Comment by jonschlinkert** [comment]
Perhaps you should use webpack with only this library to answer your own question.
