### ISSUE TITLE
Ability to use "content" block helper with the same block more than once in the same layout

### ISSUE THREAD

**Issue by d9su** [assemble/handlebars-helpers#99]
This issue is related to the {{#block}} and {{#content}} helper. Currently if I define a block in a layout, and that layout includes multiple partials each defining their own corresponding content, they overwrite each other and only the one that comes in the last gets injected into layout. The ideal case is if the content helpers have "append" or "prepend" mode defined they are all included in the respective fashion.

**Example:**
Layout:
```
<h1>Event Invitation</h1>
<p>Please come have fun!</p>

{{> pick-time}}

{{> contact-form}}

{{#block "script"}}
{{/block}}

```

Partial "pick-time":
```
<div>Pick your time slot ... </div>
{{#content "script"}}
    some script
{{/content}}
```

Partial "contact-form":
```
<div>Contact form</div>
{{#content "script"}}
    some other script
{{/content}}
```

Currently only the script from the contact-form gets injected.

**Comment by brunowego** [comment]
+1

**Comment by brunowego** [comment]
@taurose, please create a PR with this fix :+1:

**Comment by jonschlinkert** [comment]
@shannonmoeller created a [far better helper](https://github.com/shannonmoeller/handlebars-layouts) that we'll be using in the next release (which is ready besides docs).

**Comment by custa1200** [comment]
I Just tried to add a heap of scripts from different partials to my main layout using 
```
{{#block "scripts"}}
```
and in my partials I have 
```
{{#content "scripts"mode=""append"}}
...
{{/content}}
```
But as other have stated the only one to be rendered  is the last one in the execution order.What is the best way to resolve this?

**Comment by custa1200** [comment]
So register @shannonmoeller's handlebars-layouts after the express-helpers and using the same type of markup works. Any idea when this might just get rolled back into the helpers repository?
